# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sandglass_pb2 as sandglass__pb2


class BrokerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTopic = channel.unary_unary(
        '/sandglass.BrokerService/CreateTopic',
        request_serializer=sandglass__pb2.TopicConfig.SerializeToString,
        response_deserializer=sandglass__pb2.TopicReply.FromString,
        )
    self.GetTopic = channel.unary_unary(
        '/sandglass.BrokerService/GetTopic',
        request_serializer=sandglass__pb2.GetTopicParams.SerializeToString,
        response_deserializer=sandglass__pb2.GetTopicReply.FromString,
        )
    self.Produce = channel.unary_unary(
        '/sandglass.BrokerService/Produce',
        request_serializer=sandglass__pb2.ProduceMessageRequest.SerializeToString,
        response_deserializer=sandglass__pb2.ProduceResponse.FromString,
        )
    self.FetchFrom = channel.unary_stream(
        '/sandglass.BrokerService/FetchFrom',
        request_serializer=sandglass__pb2.FetchFromRequest.SerializeToString,
        response_deserializer=sandglass__pb2.Message.FromString,
        )
    self.FetchRange = channel.unary_stream(
        '/sandglass.BrokerService/FetchRange',
        request_serializer=sandglass__pb2.FetchRangeRequest.SerializeToString,
        response_deserializer=sandglass__pb2.Message.FromString,
        )
    self.ConsumeFromGroup = channel.unary_stream(
        '/sandglass.BrokerService/ConsumeFromGroup',
        request_serializer=sandglass__pb2.ConsumeFromGroupRequest.SerializeToString,
        response_deserializer=sandglass__pb2.Message.FromString,
        )
    self.Acknowledge = channel.unary_unary(
        '/sandglass.BrokerService/Acknowledge',
        request_serializer=sandglass__pb2.MarkRequest.SerializeToString,
        response_deserializer=sandglass__pb2.MarkResponse.FromString,
        )
    self.NotAcknowledge = channel.unary_unary(
        '/sandglass.BrokerService/NotAcknowledge',
        request_serializer=sandglass__pb2.MarkRequest.SerializeToString,
        response_deserializer=sandglass__pb2.MarkResponse.FromString,
        )
